data:
  common_1:
    chance: 15
    items: [18, 1]
  common_2:
    chance: 15
    items: [19, 1]
  common_3:
    chance: 15
    items: [12, 1]
  common_4:
    chance: 15
    items: [21, 1]
  uncommon_1:
    chance: 10
    items: [8, 1]
  uncommon_2:
    chance: 10
    items: [14, 1]
  uncommon_3:
    chance: 5
    items: [15, 1]
  rare_1:
    chance: 5
    items: [2]
  rare_2:
    chance: 5
    items: [13, 1]
  epic_1:
    chance: 3
    items: [7, 1]
  epic_2:
    chance: 3
    items: [10, 1]
  legendary_1:
    chance: 2
    items: [9, 1]
  legendary_2:
    chance: 2
    items: [11, 1]
  legendary_3:
    chance: 1
    items: [16, 1]
  legendary_4:
    chance: 1
    items: [17, 1]
  legendary_5:
    chance: 1
    items: [20, 1]
  legendary_6:
    chance: 1
    items: [22, 1]